async function getJsPDF() {
  const { default: jsPDF } = await import("jspdf");
  return jsPDF;
}

function addHeader(doc, title) {
  doc.setFillColor(10, 22, 40);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(201, 151, 43);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("JurisTech", 15, 18);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("juristech.com.ng | 08067234189 | Suite 412, MKK Plaza, Jabi Abuja", 15, 27);

  doc.setTextColor(10, 22, 40);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, 15, 52);

  doc.setDrawColor(201, 151, 43);
  doc.setLineWidth(0.8);
  doc.line(15, 56, 195, 56);
}

function addFooter(doc, pageCount) {
  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(201, 151, 43);
  doc.setLineWidth(0.5);
  doc.line(15, pageHeight - 25, 195, pageHeight - 25);

  doc.setFontSize(7);
  doc.setTextColor(107, 114, 128);
  doc.setFont("helvetica", "italic");
  doc.text(
    "Generated by JurisTech | juristech.com.ng | This document is a template. For legal advice, consult a qualified Nigerian lawyer.",
    15,
    pageHeight - 18
  );

  doc.setFont("helvetica", "normal");
  doc.text(`Page ${pageCount}`, 195, pageHeight - 18, { align: "right" });
}

function addField(doc, label, value, y) {
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.setFont("helvetica", "normal");
  doc.text(label, 15, y);

  doc.setFontSize(10);
  doc.setTextColor(26, 26, 46);
  doc.setFont("helvetica", "normal");
  const maxWidth = 180;
  const splitText = doc.splitTextToSize(value || "N/A", maxWidth);
  doc.text(splitText, 15, y + 6);

  return y + 6 + splitText.length * 5;
}

function addFieldRow(doc, label1, value1, label2, value2, y) {
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(label1, 15, y);
  doc.text(label2, 105, y);

  doc.setFontSize(10);
  doc.setTextColor(26, 26, 46);
  doc.text(value1 || "N/A", 15, y + 6);
  doc.text(value2 || "N/A", 105, y + 6);

  return y + 12;
}

function addSection(doc, sectionTitle, y) {
  doc.setFillColor(245, 245, 244);
  doc.rect(15, y - 5, 180, 8, "F");

  doc.setFontSize(11);
  doc.setTextColor(10, 22, 40);
  doc.setFont("helvetica", "bold");
  doc.text(sectionTitle, 18, y);

  return y + 10;
}

function addClause(doc, number, title, content, y) {
  const maxWidth = 175;

  doc.setFontSize(10);
  doc.setTextColor(10, 22, 40);
  doc.setFont("helvetica", "bold");
  doc.text(`${number}. ${title}`, 18, y);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.setFont("helvetica", "normal");
  const splitContent = doc.splitTextToSize(content, maxWidth);
  doc.text(splitContent, 18, y + 6);

  return y + 6 + splitContent.length * 4.5 + 4;
}

function checkPageBreak(doc, y, required = 30) {
  const pageHeight = doc.internal.pageSize.height;
  if (y + required > pageHeight - 30) {
    doc.addPage();
    return 20;
  }
  return y;
}

export async function generateTenancyAgreement(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "RESIDENTIAL TENANCY AGREEMENT");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 5;

  y = addSection(doc, "Parties", y);
  y = addField(doc, "Landlord:", data.landlordName, y);
  y = addField(doc, "Address:", data.landlordAddress, y);
  y += 3;
  y = addField(doc, "Tenant:", data.tenantName, y);
  y = addField(doc, "Phone:", data.tenantPhone, y);
  y += 8;

  y = addSection(doc, "Property Details", y);
  y = addField(doc, "Property Address:", data.propertyAddress, y);
  y = addField(doc, "Property Type:", data.propertyType, y);
  y += 8;

  y = addSection(doc, "Terms", y);
  y = addField(doc, "Annual Rent:", `₦${Number(data.rentAmount).toLocaleString()}`, y);
  y = addField(doc, "Tenancy Period:", `${new Date(data.startDate).toLocaleDateString("en-NG")} to ${new Date(data.endDate).toLocaleDateString("en-NG")}`, y);
  y += 8;

  y = addSection(doc, "Terms & Conditions", y);
  const clauses = [
    { title: "Payment of Rent", content: `The Tenant shall pay the sum of ₦${Number(data.rentAmount).toLocaleString()} as annual rent for the property described above, payable in advance on the commencement date of this tenancy.` },
    { title: "Use of Property", content: "The property shall be used exclusively for residential purposes and shall not be used for any illegal or immoral purposes." },
    { title: "Maintenance", content: "The Tenant shall keep the interior of the property in good and tenantable condition, fair wear and tear excepted. The Landlord shall be responsible for structural repairs." },
    { title: "Alterations", content: "The Tenant shall not make any structural alterations or additions to the property without the prior written consent of the Landlord." },
    { title: "Subletting", content: "The Tenant shall not sublet, assign, or part with possession of the property or any part thereof without the written consent of the Landlord." },
    { title: "Utilities", content: "The Tenant shall be responsible for payment of all utility bills including electricity, water, and waste disposal during the tenancy period." },
    { title: "Notice to Quit", content: "Either party may terminate this agreement by giving the other party not less than three (3) months' written notice prior to the expiry date." },
    { title: "Governing Law", content: `This agreement shall be governed by the laws of the Federal Republic of Nigeria, ${data.state} State. Any disputes arising shall be subject to the jurisdiction of courts in ${data.state} State.` },
  ];

  clauses.forEach((clause, i) => {
    y = checkPageBreak(doc, y, 25);
    y = addClause(doc, i + 1, clause.title, clause.content, y);
  });

  y += 15;
  y = checkPageBreak(doc, y, 40);
  y = addSection(doc, "Signatures", y);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("Landlord:", 18, y);
  doc.text("Tenant:", 105, y);
  y += 20;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(18, y, 80, y);
  doc.line(105, y, 167, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(data.landlordName, 18, y);
  doc.text(data.tenantName, 105, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generateServiceAgreement(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "SERVICE AGREEMENT");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 5;

  y = addSection(doc, "Parties", y);
  y = addField(doc, "Service Provider:", data.providerName, y);
  y = addField(doc, "Address:", data.providerAddress, y);
  y += 3;
  y = addField(doc, "Client:", data.clientName, y);
  y = addField(doc, "Address:", data.clientAddress, y);
  y += 8;

  y = addSection(doc, "Service Details", y);
  y = addField(doc, "Description:", data.serviceDescription, y);
  y = addField(doc, "Total Fee:", `₦${Number(data.feeAmount).toLocaleString()}`, y);
  y = addField(doc, "Payment Terms:", data.paymentTerms, y);
  y = addField(doc, "Period:", `${new Date(data.startDate).toLocaleDateString("en-NG")} to ${new Date(data.deliveryDate).toLocaleDateString("en-NG")}`, y);
  y += 8;

  y = addSection(doc, "Terms & Conditions", y);
  const clauses = [
    { title: "Scope of Services", content: `The Service Provider agrees to provide the services described as: "${data.serviceDescription}" to the Client in a professional and timely manner.` },
    { title: "Compensation", content: `The Client agrees to pay the Service Provider the sum of ₦${Number(data.feeAmount).toLocaleString()} for the services rendered, according to the payment terms: ${data.paymentTerms}.` },
    { title: "Timeline", content: `The Service Provider shall commence work on ${new Date(data.startDate).toLocaleDateString("en-NG")} and deliver the completed services on or before ${new Date(data.deliveryDate).toLocaleDateString("en-NG")}.` },
    { title: "Confidentiality", content: "Both parties agree to keep confidential all proprietary information disclosed during the course of this agreement." },
    { title: "Intellectual Property", content: "Upon full payment, all intellectual property rights in the deliverables shall transfer to the Client. Until full payment, all rights remain with the Service Provider." },
    { title: "Termination", content: "Either party may terminate this agreement with fourteen (14) days' written notice. The Client shall pay for all work completed up to the date of termination." },
    { title: "Limitation of Liability", content: "The Service Provider's total liability under this agreement shall not exceed the total fee paid by the Client." },
    { title: "Governing Law", content: `This agreement shall be governed by the laws of the Federal Republic of Nigeria, ${data.state} State. Any disputes shall be resolved through the courts of ${data.state} State.` },
  ];

  clauses.forEach((clause, i) => {
    y = checkPageBreak(doc, y, 25);
    y = addClause(doc, i + 1, clause.title, clause.content, y);
  });

  y += 15;
  y = checkPageBreak(doc, y, 40);
  y = addSection(doc, "Signatures", y);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("Service Provider:", 18, y);
  doc.text("Client:", 105, y);
  y += 20;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(18, y, 80, y);
  doc.line(105, y, 167, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(data.providerName, 18, y);
  doc.text(data.clientName, 105, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generateNDA(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "NON-DISCLOSURE AGREEMENT");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 5;

  y = addSection(doc, "Parties", y);
  y = addField(doc, "Disclosing Party:", data.disclosingParty, y);
  y = addField(doc, "Address:", data.disclosingAddress, y);
  y += 3;
  y = addField(doc, "Receiving Party:", data.receivingParty, y);
  y = addField(doc, "Address:", data.receivingAddress, y);
  y += 3;
  y = addField(doc, "Purpose:", data.purpose, y);
  y += 8;

  y = addSection(doc, "Terms & Conditions", y);
  const clauses = [
    { title: "Definition of Confidential Information", content: "Confidential Information includes all non-public information, whether in written, oral, electronic, or other form, disclosed by the Disclosing Party to the Receiving Party, including but not limited to business plans, financial information, technical data, trade secrets, client lists, and proprietary processes." },
    { title: "Obligations of Receiving Party", content: "The Receiving Party agrees to: (a) hold all Confidential Information in strict confidence; (b) not disclose such information to any third party without prior written consent; (c) use the information solely for the Purpose described above; and (d) take reasonable precautions to protect the confidentiality of the information." },
    { title: "Exclusions", content: "Confidential Information does not include information that: (a) is publicly known at the time of disclosure; (b) becomes publicly known through no fault of the Receiving Party; (c) was rightfully in the Receiving Party's possession before disclosure; or (d) is independently developed by the Receiving Party." },
    { title: "Duration", content: `The obligations of confidentiality shall remain in effect for a period of ${data.duration} from the date of this agreement.` },
    { title: "Return of Materials", content: "Upon written request by the Disclosing Party, the Receiving Party shall promptly return or destroy all Confidential Information and provide written certification of such destruction." },
    { title: "Remedies", content: "The Receiving Party acknowledges that unauthorized disclosure may cause irreparable harm. The Disclosing Party shall be entitled to seek injunctive relief in addition to any other remedies available at law." },
    { title: "Governing Law", content: `This agreement shall be governed by the laws of the Federal Republic of Nigeria, ${data.state} State. Any disputes shall be subject to the exclusive jurisdiction of the courts in ${data.state} State.` },
  ];

  clauses.forEach((clause, i) => {
    y = checkPageBreak(doc, y, 25);
    y = addClause(doc, i + 1, clause.title, clause.content, y);
  });

  y += 15;
  y = checkPageBreak(doc, y, 40);
  y = addSection(doc, "Signatures", y);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("Disclosing Party:", 18, y);
  doc.text("Receiving Party:", 105, y);
  y += 20;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(18, y, 80, y);
  doc.line(105, y, 167, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(data.disclosingParty, 18, y);
  doc.text(data.receivingParty, 105, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generateEmploymentLetter(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "EMPLOYMENT OFFER LETTER");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 8;

  y = addField(doc, "To:", data.employeeName, y);
  y = addField(doc, "Address:", data.employeeAddress, y);
  y += 10;

  y = addField(doc, "Dear " + data.employeeName.split(" ")[0] + ",", "", y);
  y += 10;

  y = addSection(doc, "Offer of Employment", y);
  const introText = `We are pleased to offer you the position of ${data.position} in the ${data.department} department at ${data.companyName}. This offer is subject to the terms and conditions outlined below.`;
  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.setFont("helvetica", "normal");
  const splitIntro = doc.splitTextToSize(introText, 175);
  doc.text(splitIntro, 15, y);
  y += splitIntro.length * 5 + 8;

  y = addSection(doc, "Employment Details", y);
  y = addField(doc, "Position:", data.position, y);
  y = addField(doc, "Department:", data.department, y);
  y = addField(doc, "Annual Salary:", `₦${Number(data.salary).toLocaleString()}`, y);
  y = addField(doc, "Start Date:", new Date(data.startDate).toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y = addField(doc, "Probation Period:", `${data.probationMonths} months`, y);
  y += 8;

  y = addSection(doc, "Terms & Conditions", y);
  const clauses = [
    { title: "Probation", content: `Your employment will be subject to a probationary period of ${data.probationMonths} months from your start date. During this period, either party may terminate the employment with one (1) week's notice.` },
    { title: "Working Hours", content: "Your normal working hours shall be 8:00 AM to 5:00 PM, Monday to Friday, with a one-hour lunch break. Additional hours may be required as business demands." },
    { title: "Leave Entitlement", content: "You are entitled to twenty (20) working days of paid annual leave per calendar year, accrued pro-rata." },
    { title: "Confidentiality", content: "You shall not disclose any confidential information relating to the company's business, clients, or operations to any third party during or after your employment." },
    { title: "Termination", content: "After probation, either party may terminate this employment by giving one (1) month's written notice or payment of one month's salary in lieu of notice." },
    { title: "Governing Law", content: `This employment shall be governed by the Nigerian Labour Act and the laws of the Federal Republic of Nigeria, ${data.state} State.` },
  ];

  clauses.forEach((clause, i) => {
    y = checkPageBreak(doc, y, 25);
    y = addClause(doc, i + 1, clause.title, clause.content, y);
  });

  y += 10;
  y = checkPageBreak(doc, y, 40);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("We look forward to having you join our team.", 15, y);
  y += 10;
  doc.text("Yours sincerely,", 15, y);
  y += 15;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(15, y, 80, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(`For: ${data.companyName}`, 15, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generateLoanAgreement(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "LOAN AGREEMENT");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 5;

  y = addSection(doc, "Parties", y);
  y = addField(doc, "Lender:", data.lenderName, y);
  y = addField(doc, "Address:", data.lenderAddress, y);
  y += 3;
  y = addField(doc, "Borrower:", data.borrowerName, y);
  y = addField(doc, "Address:", data.borrowerAddress, y);
  y += 8;

  y = addSection(doc, "Loan Details", y);
  y = addField(doc, "Loan Amount:", `₦${Number(data.loanAmount).toLocaleString()}`, y);
  y = addField(doc, "Interest Rate:", data.interestRate ? `${data.interestRate}%` : "0% (Interest-free)", y);
  y = addField(doc, "Repayment Due Date:", new Date(data.repaymentDate).toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y = addField(doc, "Repayment Method:", data.repaymentMethod, y);
  if (data.purpose) {
    y = addField(doc, "Purpose:", data.purpose, y);
  }
  y += 8;

  y = addSection(doc, "Terms & Conditions", y);
  const totalRepayment = data.interestRate
    ? Number(data.loanAmount) + (Number(data.loanAmount) * Number(data.interestRate) / 100)
    : Number(data.loanAmount);

  const clauses = [
    { title: "Loan Amount", content: `The Lender agrees to lend to the Borrower the sum of ₦${Number(data.loanAmount).toLocaleString()} (the "Loan").` },
    { title: "Interest", content: data.interestRate
      ? `The Loan shall bear interest at the rate of ${data.interestRate}% per annum. The total amount repayable shall be ₦${Number(totalRepayment).toLocaleString()}.`
      : "This Loan is interest-free. The Borrower shall repay only the principal sum of ₦" + Number(data.loanAmount).toLocaleString() + "." },
    { title: "Repayment", content: `The Borrower agrees to repay the Loan (plus interest where applicable) by ${new Date(data.repaymentDate).toLocaleDateString("en-NG")} through ${data.repaymentMethod.toLowerCase()}.` },
    { title: "Default", content: "If the Borrower fails to repay the Loan by the due date, the Lender reserves the right to pursue legal action to recover the outstanding amount plus any reasonable costs incurred in the recovery process." },
    { title: "Prepayment", content: "The Borrower may repay the Loan in whole or in part before the due date without any penalty." },
    { title: "Governing Law", content: `This agreement shall be governed by the laws of the Federal Republic of Nigeria, ${data.state} State. Any disputes shall be subject to the jurisdiction of the courts in ${data.state} State.` },
  ];

  clauses.forEach((clause, i) => {
    y = checkPageBreak(doc, y, 25);
    y = addClause(doc, i + 1, clause.title, clause.content, y);
  });

  y += 15;
  y = checkPageBreak(doc, y, 40);
  y = addSection(doc, "Signatures", y);

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("Lender:", 18, y);
  doc.text("Borrower:", 105, y);
  y += 20;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(18, y, 80, y);
  doc.line(105, y, 167, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(data.lenderName, 18, y);
  doc.text(data.borrowerName, 105, y);

  y += 12;
  doc.text("Witness:", 18, y);
  y += 20;
  doc.line(18, y, 80, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generateDemandLetter(data) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF();
  let y = 65;

  addHeader(doc, "LETTER OF DEMAND");

  y = addField(doc, "Date:", new Date().toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" }), y);
  y += 8;

  y = addField(doc, "To:", data.recipientName, y);
  y = addField(doc, "Address:", data.recipientAddress, y);
  y += 10;

  y = addSection(doc, "RE: DEMAND FOR PAYMENT OF ₦" + Number(data.amountOwed).toLocaleString(), y);
  y += 5;

  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.setFont("helvetica", "normal");

  const bodyText = `Dear ${data.recipientName.split(" ")[0]},`;
  doc.text(bodyText, 15, y);
  y += 8;

  const introText = `I write to formally demand the payment of ₦${Number(data.amountOwed).toLocaleString()} which you currently owe me. The outstanding amount relates to: ${data.debtDescription}`;
  const splitIntro = doc.splitTextToSize(introText, 175);
  doc.text(splitIntro, 15, y);
  y += splitIntro.length * 5 + 8;

  const deadlineText = `You are hereby required to pay the full amount of ₦${Number(data.amountOwed).toLocaleString()} on or before ${new Date(data.dueDate).toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}. Payment should be made directly to me or to my designated account.`;
  const splitDeadline = doc.splitTextToSize(deadlineText, 175);
  doc.text(splitDeadline, 15, y);
  y += splitDeadline.length * 5 + 10;

  y = checkPageBreak(doc, y, 25);

  const warningText = "TAKE NOTICE that if you fail to comply with this demand within the stipulated period, I shall be compelled to take legal action against you to recover the outstanding sum, together with interest and all legal costs incurred, without further notice to you.";
  const splitWarning = doc.splitTextToSize(warningText, 175);
  doc.text(splitWarning, 15, y);
  y += splitWarning.length * 5 + 10;

  const closingText = "I trust that you will treat this matter with the urgency it deserves and make payment promptly to avoid unnecessary legal proceedings.";
  const splitClosing = doc.splitTextToSize(closingText, 175);
  doc.text(splitClosing, 15, y);
  y += splitClosing.length * 5 + 15;

  doc.text("Yours faithfully,", 15, y);
  y += 15;
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.line(15, y, 80, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(data.senderName, 15, y);
  y += 4;
  doc.text(data.senderAddress, 15, y);

  addFooter(doc, doc.internal.getNumberOfPages());

  return doc;
}

export async function generatePDF(docType, data) {
  const generators = {
    "tenancy-agreement": generateTenancyAgreement,
    "service-agreement": generateServiceAgreement,
    "nda": generateNDA,
    "employment-letter": generateEmploymentLetter,
    "loan-agreement": generateLoanAgreement,
    "demand-letter": generateDemandLetter,
  };

  const generator = generators[docType];
  if (!generator) throw new Error("Unknown document type");

  return generator(data);
}
